### ISSUE TITLE
How to make hotkey shortcut for dynamic command that is itself dynamic

### ISSUE THREAD

**Issue by gaufde** [zeitlings/alfred-quill#4]
Hello,

I think I've figured out how to make a shortcut for a dynamic command that is static. For example, if I want to wrap text in `%`, I can use `|wrap|%{var:delim}%{var:trigger}Ͽ` as the prefix:

<img width="529" alt="image" src="https://github.com/user-attachments/assets/e886f21e-0f15-47e5-a1b3-de6c8cdfddee">

However, I would really like to make a hotkey that is equivalent to using the dynamic `Wrap in...` command where I can specify my own wrapping strings. That way, the workflow would be `select text in MacOS` -> `hotkey trigger` -> `type wrapping text (e.g. %;%)` -> `done!`

Is it possible to make a hotkey trigger for a _dynamic_ dynamic command?

**Comment by gaufde** [comment]
@zeitlings Thanks for the quick help! I got it working perfectly by adding a `Hotkey`, `Split Arg`, and `Arg and Vars` objects with the configurations you showed in the screenshots.

>You could create a new [external trigger](https://www.alfredapp.com/help/workflows/triggers/external/) object, similar to the existing trigger with identifier "direct", to set up a number of new hotkeys of this kind in the same fashion as the hotkeys from the examples.

Can you explain a bit more about this? I'm not sure I fully understand why I would want to do it this way. It is just easier to maintain over time?

**Comment by zeitlings** [comment]
> Can you explain a bit more about this? I'm not sure I fully understand why I would want to do it this way. It is just easier to maintain over time?

Exactly. It's simply to avoid cluttering the top of the canvas and to provide a dedicated section for these types of triggers. Otherwise, there's no urgent need to set it up this way. 

> I got it working perfectly by adding a Hotkey, Split Arg, and Arg and Vars objects with the configurations you showed in the screenshots.

Nice! I'm glad it worked out for you.

**Comment by gaufde** [comment]
>Exactly. It's simply to avoid cluttering the top of the canvas and to provide a dedicated section for these types of triggers. Otherwise, there's no urgent need to set it up this way.

That makes sense! I think I'd like to try that method, but I might need a bit more clarification if you have the time.

The external trigger you referenced looks like this:
<img width="644" alt="image" src="https://github.com/user-attachments/assets/ebf8ed90-5889-4636-a41d-563e22aef924">

How do I use that in combination with Hotkeys to set up a dynamic trigger like you were suggesting?

Do I make my own workflow where I bind some hotkey triggers to script actions that interact though AppleScripts?

**Comment by zeitlings** [comment]
> How do I use that in combination with Hotkeys to set up a dynamic trigger like you were suggesting?

You would create a new [External Trigger](https://www.alfredapp.com/help/workflows/triggers/external/) object and give it, for example, the identifier `indirect`. This external trigger object should then point into the Script Filter, just like the Args and Vars utility does now. The Args and Vars utility, Instead of pointing into the Script Filter, now points into an [Call External Trigger](https://www.alfredapp.com/help/workflows/outputs/call-external-trigger/) object that references the External Trigger with ID `indirect`. 

<img width="500" alt="quill-indirect-1" src="https://github.com/user-attachments/assets/092b5d61-1c03-4b40-bd20-9fba6ae7e3ec">
<img width="500" alt="quill-indirect-2" src="https://github.com/user-attachments/assets/d372189f-7131-4dbf-82c0-fe1395e25308">
<img width="500" alt="quill-indirect-3" src="https://github.com/user-attachments/assets/16532db3-fa99-4feb-91af-ecbe146f50bc">  

That way you can move the Hotkeys anywhere and reuse the split and args & vars components.   

> Do I make my own workflow where I bind some hotkey triggers to script actions that interact though AppleScripts?

I would even recommend setting up a new workflow for your customizations! That way your changes won't be lost when there is an update to the workflow.

**Comment by gaufde** [comment]
Thanks so much for the extra help! That worked perfectly to create my trigger in an external workflow. Also, its a good way to get my feet wet with Alfred workflows.
